/**
 * @file types/meeting.ts
 * @description Centralized TypeScript type definitions for the entire application.
 *
 * Having all shared types in one place means:
 *  - A single source of truth — change a type once, it updates everywhere.
 *  - Easier onboarding — a new developer can read this file to understand all data shapes.
 *  - No circular imports from components importing types from each other.
 */

// ===========================================================================
// MEETING TYPES
// ===========================================================================

/** A scheduled or instant meeting created by a host. */
export interface Meeting {
  id: string;
  meeting_code: string;
  title: string;
  start_time: string;        // ISO-8601 UTC string from the backend
  duration: number;          // Duration in minutes
  is_instant: boolean;       // true = "New Meeting" button, false = scheduled
  is_ended: boolean;         // Host has explicitly ended the meeting
  host_id: string;           // Email of the host user
}

// ===========================================================================
// PARTICIPANT TYPES
// ===========================================================================

/** Status of a participant in the meeting lobby/room. */
export type ParticipantStatus = 'waiting' | 'admitted';

/**
 * A participant who has joined (or is waiting to join) a meeting.
 * Returned by the /join API and updated via WebSocket messages.
 */
export interface Participant {
  id: string;
  display_name: string;
  is_host: boolean;
  status: ParticipantStatus;
  audio_enabled: boolean;
  video_enabled: boolean;
  hand_raised: boolean;
  /** Zego App ID — 0 in mock/dev mode */
  zego_app_id: number;
  /** Short-lived Zego room token generated by the backend */
  token: string;
}

// ===========================================================================
// CHAT TYPES
// ===========================================================================

/** A single chat message in the meeting room. */
export interface ChatMessage {
  type: 'CHAT_MESSAGE';
  sender_name: string;
  sender_id: string;
  message_text: string;
  /** ISO timestamp — set by the backend on receipt */
  timestamp?: string;
  /** null = broadcast to everyone; a participant ID = private DM */
  target_user_id: string | null;
}

// ===========================================================================
// REACTION TYPES
// ===========================================================================

/**
 * A floating emoji reaction shown as an animated overlay.
 * Created locally on send and cleaned up after the animation completes.
 */
export interface FloatingReaction {
  /** Unique random ID used as React key and for cleanup */
  id: string;
  /** The emoji character, e.g. "👍" */
  emoji: string;
  /** Horizontal position as a percentage (0–100) for the animation start */
  x: number;
  /** Display name of the participant who sent the reaction */
  sender: string;
}

// ===========================================================================
// WEBSOCKET MESSAGE TYPES
// ===========================================================================

/**
 * Union of all WebSocket message types the client can receive.
 * Useful for exhaustive switch statements in the message handler.
 */
export type WsMessageType =
  | 'CHAT_MESSAGE'
  | 'REACTION'
  | 'HOST_COMMAND'
  | 'MEETING_ENDED'
  | 'KICKED'
  | 'STATE_UPDATE'
  | 'ADMIT_USER'
  | 'ADMIT_ALL';
